# ═══════════════════════════════════════════════════════════
#  WhatPay - Cloud Build CI/CD Pipeline
# ═══════════════════════════════════════════════════════════

steps:
  # 1. Install dependencies
  - name: 'node:20-alpine'
    entrypoint: 'npm'
    args: ['ci']
    id: 'install'

  # 2. Lint
  - name: 'node:20-alpine'
    entrypoint: 'npm'
    args: ['run', 'lint']
    id: 'lint'
    waitFor: ['install']

  # 3. Run tests
  - name: 'node:20-alpine'
    entrypoint: 'npm'
    args: ['test']
    id: 'test'
    waitFor: ['install']

  # 4. Build TypeScript
  - name: 'node:20-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']
    id: 'build'
    waitFor: ['lint', 'test']

  # 5. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/api:${SHORT_SHA}',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/api:latest',
      '-f', 'infra/docker/Dockerfile',
      '.'
    ]
    id: 'docker-build'
    waitFor: ['build']

  # 6. Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/api']
    id: 'docker-push'
    waitFor: ['docker-build']

  # 7. Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'whatpay-api-${_ENV}',
      '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/api:${SHORT_SHA}',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--port', '3000',
      '--quiet'
    ]
    id: 'deploy'
    waitFor: ['docker-push']

substitutions:
  _REGION: southamerica-west1
  _ENV: staging
  _REPO: whatpay-staging

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'
